repos:
  - repo: local
    hooks:
      - id: make-lint
        name: Make Lint
        entry: make lint
        language: system
        always_run: true
        pass_filenames: false
      - id: make-format
        name: Make Format
        entry: make format
        language: system
        always_run: true
        pass_filenames: false
      - id: make-sort
        name: Make Sort
        entry: make sort
        language: system
        always_run: true
        pass_filenames: false