version: '3.8'
services:
  api:
    build: ./api
    command: uvicorn main:app --host 0.0.0.0 --port 8000
    volumes:
      - ./api:/usr/src/app/api  # Make sure this matches the structure in your Dockerfile
    ports:
      - "8000:8000"
    depends_on:
      - db
    environment:
      - DATABASE_URL=postgresql://user:password@db:5432/mydatabase
      - PYTHONPATH=/usr/src/app

  db:
    image: postgres:latest
    volumes:
      - postgres_data:/var/lib/postgresql/data
    environment:
      - POSTGRES_USER=user
      - POSTGRES_PASSWORD=password
      - POSTGRES_DB=mydatabase

  frontend:
    build: ./frontend
    ports:
      - "3000:80"
    depends_on:
      - api

volumes:
  postgres_data: