"""token_revoked_fields2

Revision ID: 62d330e10ac0
Revises: 65fac7eefea6
Create Date: 2024-04-24 01:04:40.379976

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '62d330e10ac0'
down_revision: Union[str, None] = '65fac7eefea6'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('tokens', sa.Column('revoked', sa.Boolean(), nullable=True))
    op.drop_column('tokens', 'used')
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('tokens', sa.Column('used', sa.BOOLEAN(), autoincrement=False, nullable=True))
    op.drop_column('tokens', 'revoked')
    # ### end Alembic commands ###
