"""token_revoked_fields

Revision ID: 65fac7eefea6
Revises: 6a50f368dc95
Create Date: 2024-04-24 00:49:21.044885

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '65fac7eefea6'
down_revision: Union[str, None] = '6a50f368dc95'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('tokens', sa.Column('used', sa.Boolean(), nullable=True))
    op.add_column('tokens', sa.Column('revoked_at', sa.DateTime(), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('tokens', 'revoked_at')
    op.drop_column('tokens', 'used')
    # ### end Alembic commands ###
