"""vouchers of generated codes

Revision ID: 944d2eabaf1e
Revises: f04486d72d34
Create Date: 2024-05-21 22:52:28.459073

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '944d2eabaf1e'
down_revision: Union[str, None] = 'f04486d72d34'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('vouchers', sa.Column('number_of_generated_codes', sa.Integer(), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('vouchers', 'number_of_generated_codes')
    # ### end Alembic commands ###
