"""promo metadata

Revision ID: 9ca7e2645c08
Revises: 944d2eabaf1e
Create Date: 2024-06-14 02:25:39.166471

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '9ca7e2645c08'
down_revision: Union[str, None] = '944d2eabaf1e'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('voucher_codes', sa.Column('code_metadata', sa.JSON(), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('voucher_codes', 'code_metadata')
    # ### end Alembic commands ###
